# Generated by Django 4.2.16 on 2024-09-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_text',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
